// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CMD.proto

package com.game.Protobuf;

public final class CMD {
  private CMD() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  /**
   * Protobuf enum {@code com.game.Protobuf.CCMD}
   */
  public enum CCMD
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>C_Connect = 1;</code>
     */
    C_Connect(1),
    /**
     * <code>C_Disconnect = 2;</code>
     */
    C_Disconnect(2),
    /**
     * <code>C_Guest = 3;</code>
     */
    C_Guest(3),
    /**
     * <code>C_Registered = 5;</code>
     */
    C_Registered(5),
    /**
     * <code>C_Login = 6;</code>
     */
    C_Login(6),
    /**
     * <code>C_Switch = 7;</code>
     */
    C_Switch(7),
    /**
     * <code>C_LogOut = 8;</code>
     */
    C_LogOut(8),
    /**
     * <code>C_CLRegisterModel = 9;</code>
     */
    C_CLRegisterModel(9),
    /**
     * <code>C_CLIdentity = 10;</code>
     */
    C_CLIdentity(10),
    /**
     * <code>C_OCIdentity = 11;</code>
     */
    C_OCIdentity(11),
    /**
     * <code>C_GCRegisterModel = 12;</code>
     */
    C_GCRegisterModel(12),
    /**
     * <code>C_OGEntryGame = 13;</code>
     */
    C_OGEntryGame(13),
    /**
     * <code>C_GOGetGameIDInfo = 14;</code>
     */
    C_GOGetGameIDInfo(14),
    /**
     * <pre>
     *开火
     * </pre>
     *
     * <code>C_OGOnFire = 15;</code>
     */
    C_OGOnFire(15),
    /**
     * <pre>
     *撒网
     * </pre>
     *
     * <code>C_OGOnNet = 16;</code>
     */
    C_OGOnNet(16),
    /**
     * <pre>
     *全屏炸弹
     * </pre>
     *
     * <code>C_OGOnSceenBomb = 17;</code>
     */
    C_OGOnSceenBomb(17),
    ;

    /**
     * <code>C_Connect = 1;</code>
     */
    public static final int C_Connect_VALUE = 1;
    /**
     * <code>C_Disconnect = 2;</code>
     */
    public static final int C_Disconnect_VALUE = 2;
    /**
     * <code>C_Guest = 3;</code>
     */
    public static final int C_Guest_VALUE = 3;
    /**
     * <code>C_Registered = 5;</code>
     */
    public static final int C_Registered_VALUE = 5;
    /**
     * <code>C_Login = 6;</code>
     */
    public static final int C_Login_VALUE = 6;
    /**
     * <code>C_Switch = 7;</code>
     */
    public static final int C_Switch_VALUE = 7;
    /**
     * <code>C_LogOut = 8;</code>
     */
    public static final int C_LogOut_VALUE = 8;
    /**
     * <code>C_CLRegisterModel = 9;</code>
     */
    public static final int C_CLRegisterModel_VALUE = 9;
    /**
     * <code>C_CLIdentity = 10;</code>
     */
    public static final int C_CLIdentity_VALUE = 10;
    /**
     * <code>C_OCIdentity = 11;</code>
     */
    public static final int C_OCIdentity_VALUE = 11;
    /**
     * <code>C_GCRegisterModel = 12;</code>
     */
    public static final int C_GCRegisterModel_VALUE = 12;
    /**
     * <code>C_OGEntryGame = 13;</code>
     */
    public static final int C_OGEntryGame_VALUE = 13;
    /**
     * <code>C_GOGetGameIDInfo = 14;</code>
     */
    public static final int C_GOGetGameIDInfo_VALUE = 14;
    /**
     * <pre>
     *开火
     * </pre>
     *
     * <code>C_OGOnFire = 15;</code>
     */
    public static final int C_OGOnFire_VALUE = 15;
    /**
     * <pre>
     *撒网
     * </pre>
     *
     * <code>C_OGOnNet = 16;</code>
     */
    public static final int C_OGOnNet_VALUE = 16;
    /**
     * <pre>
     *全屏炸弹
     * </pre>
     *
     * <code>C_OGOnSceenBomb = 17;</code>
     */
    public static final int C_OGOnSceenBomb_VALUE = 17;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static CCMD valueOf(int value) {
      return forNumber(value);
    }

    public static CCMD forNumber(int value) {
      switch (value) {
        case 1: return C_Connect;
        case 2: return C_Disconnect;
        case 3: return C_Guest;
        case 5: return C_Registered;
        case 6: return C_Login;
        case 7: return C_Switch;
        case 8: return C_LogOut;
        case 9: return C_CLRegisterModel;
        case 10: return C_CLIdentity;
        case 11: return C_OCIdentity;
        case 12: return C_GCRegisterModel;
        case 13: return C_OGEntryGame;
        case 14: return C_GOGetGameIDInfo;
        case 15: return C_OGOnFire;
        case 16: return C_OGOnNet;
        case 17: return C_OGOnSceenBomb;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<CCMD>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        CCMD> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<CCMD>() {
            public CCMD findValueByNumber(int number) {
              return CCMD.forNumber(number);
            }
          };

    private final int value;

    private CCMD(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.game.Protobuf.CCMD)
  }

  /**
   * Protobuf enum {@code com.game.Protobuf.SCMD}
   */
  public enum SCMD
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>S_Error = 100;</code>
     */
    S_Error(100),
    /**
     * <code>S_LoginSucc = 101;</code>
     */
    S_LoginSucc(101),
    /**
     * <code>S_LoginFail = 102;</code>
     */
    S_LoginFail(102),
    /**
     * <code>S_Disconnect = 103;</code>
     */
    S_Disconnect(103),
    /**
     * <code>S_Email = 104;</code>
     */
    S_Email(104),
    /**
     * <code>S_SignIn = 105;</code>
     */
    S_SignIn(105),
    /**
     * <code>S_LCRegisterModel = 106;</code>
     */
    S_LCRegisterModel(106),
    /**
     * <code>S_LCIdentity = 107;</code>
     */
    S_LCIdentity(107),
    /**
     * <code>S_COUserData = 108;</code>
     */
    S_COUserData(108),
    /**
     * <code>S_CORoomList = 109;</code>
     */
    S_CORoomList(109),
    /**
     * <code>S_GOGamePlayerInfo = 150;</code>
     */
    S_GOGamePlayerInfo(150),
    /**
     * <pre>
     * 场景地图
     * </pre>
     *
     * <code>S_GOMapInfo = 151;</code>
     */
    S_GOMapInfo(151),
    /**
     * <pre>
     *撒鱼
     * </pre>
     *
     * <code>S_GOPutFish = 152;</code>
     */
    S_GOPutFish(152),
    /**
     * <pre>
     *阵型鱼
     * </pre>
     *
     * <code>S_GOPutFishGroup = 153;</code>
     */
    S_GOPutFishGroup(153),
    /**
     * <pre>
     *开火成功
     * </pre>
     *
     * <code>S_GOFireSuccess = 154;</code>
     */
    S_GOFireSuccess(154),
    /**
     * <pre>
     *开火失败
     * </pre>
     *
     * <code>S_GOFireFire = 155;</code>
     */
    S_GOFireFire(155),
    /**
     * <pre>
     *撒网成功
     * </pre>
     *
     * <code>S_GONetSuccess = 156;</code>
     */
    S_GONetSuccess(156),
    /**
     * <pre>
     *打中全屏炸弹
     * </pre>
     *
     * <code>S_GOOnSceenBombSucc = 157;</code>
     */
    S_GOOnSceenBombSucc(157),
    ;

    /**
     * <code>S_Error = 100;</code>
     */
    public static final int S_Error_VALUE = 100;
    /**
     * <code>S_LoginSucc = 101;</code>
     */
    public static final int S_LoginSucc_VALUE = 101;
    /**
     * <code>S_LoginFail = 102;</code>
     */
    public static final int S_LoginFail_VALUE = 102;
    /**
     * <code>S_Disconnect = 103;</code>
     */
    public static final int S_Disconnect_VALUE = 103;
    /**
     * <code>S_Email = 104;</code>
     */
    public static final int S_Email_VALUE = 104;
    /**
     * <code>S_SignIn = 105;</code>
     */
    public static final int S_SignIn_VALUE = 105;
    /**
     * <code>S_LCRegisterModel = 106;</code>
     */
    public static final int S_LCRegisterModel_VALUE = 106;
    /**
     * <code>S_LCIdentity = 107;</code>
     */
    public static final int S_LCIdentity_VALUE = 107;
    /**
     * <code>S_COUserData = 108;</code>
     */
    public static final int S_COUserData_VALUE = 108;
    /**
     * <code>S_CORoomList = 109;</code>
     */
    public static final int S_CORoomList_VALUE = 109;
    /**
     * <code>S_GOGamePlayerInfo = 150;</code>
     */
    public static final int S_GOGamePlayerInfo_VALUE = 150;
    /**
     * <pre>
     * 场景地图
     * </pre>
     *
     * <code>S_GOMapInfo = 151;</code>
     */
    public static final int S_GOMapInfo_VALUE = 151;
    /**
     * <pre>
     *撒鱼
     * </pre>
     *
     * <code>S_GOPutFish = 152;</code>
     */
    public static final int S_GOPutFish_VALUE = 152;
    /**
     * <pre>
     *阵型鱼
     * </pre>
     *
     * <code>S_GOPutFishGroup = 153;</code>
     */
    public static final int S_GOPutFishGroup_VALUE = 153;
    /**
     * <pre>
     *开火成功
     * </pre>
     *
     * <code>S_GOFireSuccess = 154;</code>
     */
    public static final int S_GOFireSuccess_VALUE = 154;
    /**
     * <pre>
     *开火失败
     * </pre>
     *
     * <code>S_GOFireFire = 155;</code>
     */
    public static final int S_GOFireFire_VALUE = 155;
    /**
     * <pre>
     *撒网成功
     * </pre>
     *
     * <code>S_GONetSuccess = 156;</code>
     */
    public static final int S_GONetSuccess_VALUE = 156;
    /**
     * <pre>
     *打中全屏炸弹
     * </pre>
     *
     * <code>S_GOOnSceenBombSucc = 157;</code>
     */
    public static final int S_GOOnSceenBombSucc_VALUE = 157;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static SCMD valueOf(int value) {
      return forNumber(value);
    }

    public static SCMD forNumber(int value) {
      switch (value) {
        case 100: return S_Error;
        case 101: return S_LoginSucc;
        case 102: return S_LoginFail;
        case 103: return S_Disconnect;
        case 104: return S_Email;
        case 105: return S_SignIn;
        case 106: return S_LCRegisterModel;
        case 107: return S_LCIdentity;
        case 108: return S_COUserData;
        case 109: return S_CORoomList;
        case 150: return S_GOGamePlayerInfo;
        case 151: return S_GOMapInfo;
        case 152: return S_GOPutFish;
        case 153: return S_GOPutFishGroup;
        case 154: return S_GOFireSuccess;
        case 155: return S_GOFireFire;
        case 156: return S_GONetSuccess;
        case 157: return S_GOOnSceenBombSucc;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<SCMD>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        SCMD> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<SCMD>() {
            public SCMD findValueByNumber(int number) {
              return SCMD.forNumber(number);
            }
          };

    private final int value;

    private SCMD(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.game.Protobuf.SCMD)
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
